version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: capstone_root_password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - scanner_network

  target-wp:
    image: wordpress:5.0
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      # This maps a local folder to the container's plugin directory
      - ./vulnerable-plugins:/var/www/html/wp-content/plugins
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - scanner_network

volumes:
  db_data:

networks:
  scanner_network:
    driver: bridge
